import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '../globalComponents/navbar/Navigation'
import Footer from '@/globalComponents/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nauci programiranje',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navigation />
          {children}
          <Footer />
      </body>
    </html>
  )
}
