import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navigation/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nauci programiranje',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden mx-auto">
              <div className="w-[20em] flex-none">
                  <Navbar />
              </div>
              <div className="flex w-full overflow-hidden">
                {children}
               </div>
              </div>
      </body>
    </html>
  )
}
